import { spawn } from "node:child_process";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const DEFAULT_VOICE = "uk-UA-OstapNeural";
const DEFAULT_LANG = "uk-UA";
const LINES_PATH = path.join(ROOT, "public", "audio", "voice", "voice-lines.json");
const OUT_DIR = path.join(ROOT, "public", "audio", "voice");
const MANIFEST_PATH = path.join(ROOT, "src", "audio", "voiceManifest.js");

const args = new Map();
for (let i = 2; i < process.argv.length; i++) {
  const arg = process.argv[i];
  if (arg.startsWith("--")) {
    const key = arg.slice(2);
    const next = process.argv[i + 1];
    if (!next || next.startsWith("--")) args.set(key, true);
    else {
      args.set(key, next);
      i++;
    }
  }
}

const voice = String(args.get("voice") || process.env.VOICE || DEFAULT_VOICE);
const lang = String(args.get("lang") || process.env.LANG_CODE || DEFAULT_LANG);
const group = args.get("group") ? String(args.get("group")) : "";
const ids = args.get("id")
  ? String(args.get("id"))
      .split(",")
      .map((id) => id.trim())
      .filter(Boolean)
  : [];
const limit = args.get("limit") ? Number(args.get("limit")) : 0;
const force = Boolean(args.get("force"));

function normalizeSpeechText(text) {
  return String(text || "")
    .replace(/Роботрон-9000/g, "Роботрон девʼять тисяч")
    .replace(/Роботрон девять тисяч/g, "Роботрон девʼять тисяч")
    .replace(/ТЦК/g, "те це ка")
    .replace(/Києве/g, "Києве")
    .replace(/Слава Україні/g, "Слава Україні")
    .replace(/УРА/g, "Ура")
    .replace(/ПЕРЕМОГА/g, "Перемога")
    .replace(/[.,!?;:…"'“”„«»()[\]{}<>—–-]/g, " ")
    .replace(/[ʼ'`]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function prepareTextForTts(text) {
  return String(text || "")
    .replace(/[—–]/g, ", ")
    .replace(/\s+/g, " ")
    .trim();
}

function quoteWindowsArg(arg) {
  const value = String(arg);
  if (!/[()\s^&|<>"]/.test(value)) return value;
  return `"${value.replace(/(["^&|<>])/g, "^$1")}"`;
}

function run(command, commandArgs) {
  return new Promise((resolve, reject) => {
    const windowsCommand = [command, ...commandArgs].map(quoteWindowsArg).join(" ");
    const child = spawn(
      process.platform === "win32" ? process.env.ComSpec || "cmd.exe" : command,
      process.platform === "win32" ? ["/d", "/s", "/c", windowsCommand] : commandArgs,
      {
      cwd: ROOT,
      shell: false,
      stdio: "inherit",
      },
    );
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} exited with ${code}`));
    });
    child.on("error", reject);
  });
}

async function exists(filePath) {
  try {
    await readFile(filePath);
    return true;
  } catch {
    return false;
  }
}

function toManifest(lines) {
  const entries = lines
    .map((line) => {
      const key = normalizeSpeechText(line.text);
      const value = `/game/audio/voice/${line.id}.mp3`;
      return `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`;
    })
    .join("\n");

  return `// Generated by scripts/generate-voice.mjs.\n// Keys are normalized Ukrainian phrases after normalizeSpeechText().\nexport const VOICE_CLIPS = {\n${entries}\n};\n`;
}

const allLines = JSON.parse(await readFile(LINES_PATH, "utf8"));
let lines = allLines;
if (group) lines = lines.filter((line) => line.group === group);
if (ids.length > 0) lines = lines.filter((line) => ids.includes(line.id));
if (limit > 0) lines = lines.slice(0, limit);

console.log(`Generating ${lines.length} voice files`);
console.log(`Voice: ${voice}`);
console.log(`Language: ${lang}`);

for (const line of lines) {
  const outFile = path.join(OUT_DIR, `${line.id}.mp3`);
  if (!force && (await exists(outFile))) {
    console.log(`Skip existing ${line.id}.mp3`);
    continue;
  }
  console.log(`Generate ${line.id}.mp3`);
  await run("npx", [
    "--yes",
    "node-edge-tts@1.2.10",
    "--text",
    prepareTextForTts(line.text),
    "--filepath",
    outFile,
    "--voice",
    voice,
    "--lang",
    lang,
  ]);
}

const voiceFiles = new Set(
  (await readdir(OUT_DIR))
    .filter((file) => file.toLowerCase().endsWith(".mp3"))
    .map((file) => path.basename(file, ".mp3")),
);
const manifestLines = allLines.filter((line) => voiceFiles.has(line.id));
await writeFile(MANIFEST_PATH, toManifest(manifestLines), "utf8");
console.log(`Updated ${path.relative(ROOT, MANIFEST_PATH)}`);
